config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#login', as: 'login'
  get 'logout', to: 'sessions#logout', as: 'logout'
  get 'auth/github', as: 'github_login'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:post,:get]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks

  get '/cpanel', to: 'tasks#cpanel'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deadline.rb
class Deadline < ApplicationRecord
  has_many :tasks
  validates :timeframe, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :deadline
  belongs_to :user
  validates :verb, presence: true, uniqueness: true
  accepts_nested_attributes_for :deadline
end

app/models/user.rb
class User < ApplicationRecord
  validates :uid, uniqueness: true
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

 private
  # Getter method: find the currently logged-in user
  def current_user
    @current_user ||= User.find_by(uid: session[:user_uid])
  end
  # Setter method: establish the currently logged in user
  def current_user=(user)
    session[:user_uid] = user.uid
    session[:user_nickname] = user.nickname
  end

  # Predicate method; returns true if signed in
  def signed_in?
    # bang bang works in a bunch of languages, can test if things are true
    !!current_user  # Ruby apparently treats most things as true, including 0 and ""
  end

  # Method for protecting controller actions
  def authenticate_user
    unless signed_in?
      redirect_to login_url, notice: "Please log in first"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  def create
    auth_hash = request.env['omniauth.auth']
    @user = User.find_or_create_by(uid: auth_hash['uid']) do |user|
      user.nickname = auth_hash['info']['nickname']
      user.email = auth_hash['info']['email']
    end
    self.current_user = @user
    redirect_to tasks_url, notice: "You have logged in, welcome: #{current_user.nickname}!"
  end
  def login
  end
  def logout
    reset_session
    redirect_to login_url, notice: 'You have been logged out'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # IS THIS CORRECT BELOW? This change was manually edited from
  # https://github.com/jmynes/COM331-Userblog/commit/0d5c9aba4c9e476fdcc6e3690efd205f233b82a2

  # Authenticate users on following pages (except...)
  before_action :authenticate_user, except: [:index, :show]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    if @tasks.present?
      @reminder = @tasks.sample.verb
    end

    # @due = @tasks.sample.deadline.timeframe
    # Compare to timestamp of task creation, do some math
      #
  end

  # GET /tasks/list
  def cpanel
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        puts @task.errors.full_messages
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:verb, deadline_attributes: [:timeframe, :urgency])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
  def setup_task(task)
    task.deadline ||= Deadline.new
    task
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>New Tab</title>
    <!-- https://icons8.com/icon/set/plus/all -->
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.haml
.task_form
  = form_for setup_task(@task) do |f|
    - if @task.errors.any?
      #error_explanation
        %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
        %ul
          - @task.errors.full_messages.each do |message|
            %li= message

    .field
      = f.label "Task (verb)"
      = f.text_field :verb
    
      = f.fields_for :deadline do |deadline|
        = deadline.label "Deadline (timeframe)"
        = deadline.text_field :timeframe
        = deadline.label "Urgency (low-high)"
        = deadline.text_field :urgency

        -#= deadline.text_field :urgency
        -#= f.select :deadline, [['LOW','low'],['MEDIUM','medium'],['HIGH','high'],['ABSOLUTE','absolute']]

    .actions
      = f.submit 'Save'

app/views/tasks/cpanel.html.haml
%nav
  .fab
    = link_to tasks_path do
      %i.fa.fa-home

.container-container
  .panel
    %h1.title Listing tasks
    %h2.title View, edit, and destroy tasks
    %hr
    %table
      %tbody
        - @tasks.each do |task|
          %tr
            %td.title
              = task.verb
            %td.icon
              =link_to task do
                %i.fa.fa-eye
            %td.icon
              = link_to edit_task_path(task) do
                %i.fa.fa-pencil
            %td.icon.trash-no-bg
              = link_to task, method: :delete, data: { confirm: 'Are you sure?' } do
                %i.fa.fa-trash
    .fab.action
      = link_to new_task_path do
        %i.fa.fa-plus

app/views/tasks/edit.html.haml
%nav
  .fab
    = link_to tasks_path do
      %i.fa.fa-home

.container-container
  %h1.title Editing task

  = render 'form'

  .fab.action
    = link_to cpanel_path do
      %i.fa.fa-calendar
  .fab.action
    = link_to @task do
      %i.fa.fa-eye
  .fab.action.trash
    = link_to @task, method: :delete, data: { confirm: 'Are you sure?' } do
      %i.fa.fa-trash

app/views/tasks/index.html.haml
%nav
  .fab
    = link_to cpanel_path do
      %i.fa.fa-calendar

.container-container
  .reminder-container
    - if @tasks.present?
      %h1.reminder Did you remember to #{@reminder}?
    - else
      %h1.reminder Login and set your first task!

    .affirmation-container
      .fab.fa.fa-check
      .fab.fa.fa-times

  -#%form.searchForm{:action => "https://duckduckgo.com/?q=", :method => "get"}
  %form.searchForm{:action => "https://www.google.com/search?q=", :method => "get"}
    %input.searchBar{:autocomplete => "off", :autofocus => "autofocus", :name => "q", :placeholder => "Search Google...", :search_ => "", :type => "text"}/

  .fab.action
    = link_to new_task_path do
      %i.fa.fa-plus

app/views/tasks/new.html.haml
%nav
  .fab
    = link_to tasks_path do
      %i.fa.fa-home

.container-container
  %h1.title Add a task to the list

  = render 'form'

  -#= link_to 'home', tasks_path

app/views/tasks/show.html.haml
%nav
  .fab
    = link_to tasks_path do
      %i.fa.fa-home

.container-container
  %h1.title Task details

  %p#notice= notice

  %p.display
    Verb:
    = @task.verb
  %p.display
    Deadline:
    = @task.deadline.timeframe
  %p.display
    Urgency:
    = @task.deadline.urgency
  -# This below doesn't quite work yet.
  -#%p.display
    -#User:
    -#= @task.user

  .fab.action
    = link_to cpanel_path do
      %i.fa.fa-calendar
  .fab.action
    = link_to edit_task_path(@task) do
      %i.fa.fa-pencil
  .fab.action.trash
    = link_to @task, method: :delete, data: { confirm: 'Are you sure?' } do
      %i.fa.fa-trash